# Generated by agentseam 0.1.1 -- bundle("codex_cli"). Do not hand-edit, except the
# HANDLER block below (between "agentseam handler >>>" and "<<< agentseam handler"),
# which is exactly what this file leaves for you to fill in.
#
# Self-contained: stdlib only, no "import agentseam" anywhere in this file. Regenerate
# with `agentseam.bundler.bundle("codex_cli")` (same agentseam version -> identical bytes,
# except your own edits inside the handler block) rather than patching this by hand.
# https://github.com/open-coder-ai/agentseam

from __future__ import annotations

import json
_json = json
import sys

import os as _chock_os
import shlex as _chock_shlex
import subprocess as _chock_subprocess
from datetime import datetime as _chock_datetime, timezone as _chock_timezone
from pathlib import Path as _chock_Path

# ------------------------------------------------------------------------------
# contract (agentseam 0.1.1)

"""Canonical event vocabulary, normalized envelope, and decision type.

This is L0: the contract every adapter speaks. Nothing here knows any vendor.
Stdlib only — this module is embedded verbatim into rendered single-file adapters.
"""



# --- canonical lifecycle events -------------------------------------------------
# Vendor event names map ONTO these; adapters own the mapping. A vendor that lacks
# an event simply has no row for it in the capability matrix — that absence is the
# honest coverage floor, not something to paper over.
SESSION_START = "session_start"
SESSION_END = "session_end"
PROMPT_SUBMIT = "prompt_submit"
PRE_TOOL = "pre_tool"
POST_TOOL = "post_tool"
TOOL_FAILURE = "tool_failure"
PRE_COMPACT = "pre_compact"
STOP = "stop"
SUBAGENT_START = "subagent_start"
SUBAGENT_STOP = "subagent_stop"
INSTRUCTIONS_LOADED = "instructions_loaded"
FILE_CHANGED = "file_changed"

#: Not a lifecycle event: the honest answer when a vendor sends something this adapter has
#: no mapping for. Deliberately outside EVENTS, so a handler matching on the vocabulary can
#: never match it by accident.
#:
#: The alternative was what several adapters used to do -- fall back to the nearest
#: canonical event -- which reports an unknown event as `pre_tool` and invites a guardrail
#: to evaluate a pre-tool policy against something that is not one. New vendor events appear
#: without warning; being told is the only safe outcome.
UNKNOWN = "unknown"

EVENTS = (
    SESSION_START,
    SESSION_END,
    PROMPT_SUBMIT,
    PRE_TOOL,
    POST_TOOL,
    TOOL_FAILURE,
    PRE_COMPACT,
    STOP,
    SUBAGENT_START,
    SUBAGENT_STOP,
    INSTRUCTIONS_LOADED,
    FILE_CHANGED,
)

# --- normalized envelope --------------------------------------------------------


class Event:
    """One agent lifecycle event, normalized.

    `raw` is always kept: adapters normalize the fields consumers usually want, and
    a consumer that needs something vendor-specific can still reach it rather than
    being blocked by our vocabulary.
    """

    __slots__ = (
        "agent",
        "event",
        "tool",
        "command",
        "path",
        "content",
        "output",
        "prompt",
        "session_id",
        "tool_use_id",
        "cwd",
        "raw",
    )

    def __init__(
        self,
        agent,
        event,
        *,
        tool=None,
        command=None,
        path=None,
        content=None,
        output=None,
        prompt=None,
        session_id=None,
        tool_use_id=None,
        cwd=None,
        raw=None,
    ):
        self.agent = agent
        self.event = event
        self.tool = tool
        self.command = command  # shell command, when the tool carries one
        self.path = path  # target file, when the tool writes one
        self.content = content  # file text being written (pre_tool on write tools)
        self.output = output  # tool result (post_tool)
        self.prompt = prompt  # user prompt text (prompt_submit)
        self.session_id = session_id
        self.tool_use_id = tool_use_id
        self.cwd = cwd
        self.raw = raw if raw is not None else {}

    def __repr__(self):  # pragma: no cover - debugging aid
        return "Event(%s/%s tool=%r path=%r)" % (self.agent, self.event, self.tool, self.path)


# --- decisions ------------------------------------------------------------------

ALLOW = "allow"
DENY = "deny"
ASK = "ask"
REWRITE = "rewrite"
#: "I actively approve -- skip the user's own confirmation," never the default. ALLOW means
#: no objection; a bare ALLOW that spoke this loudly was the exact defect
#: allow_semantics.py exists to audit. VOUCH is that same loud word, used on purpose, on the
#: vendors it is established to mean this. See dispatch.degrade() and
#: allow_semantics.VOUCH_SPEAKS for which those are, and how everyone else degrades.
VOUCH = "vouch"


class Decision:
    """What a handler wants to happen. Adapters translate this to vendor dialect.

    `evidence` is an optional payload-free dict a consumer can carry through to its
    own log; agentseam never writes it anywhere itself.

    `context` is different: free text meant to reach the MODEL, on the few vendor
    surfaces that take side-channel context injection independent of the outcome
    (Claude Code's hookSpecificOutput.additionalContext at SessionStart and
    UserPromptSubmit today). An adapter with no such surface drops it silently --
    the same honest-degrade shape as an unsupported outcome, not a promise every
    vendor can keep. It is advisory content, never a substitute for `reason`, which
    still speaks to the vendor's own decision/refusal dialect.
    """

    __slots__ = ("outcome", "reason", "updated_input", "evidence", "context")

    def __init__(self, outcome, reason=None, updated_input=None, evidence=None, context=None):
        if outcome not in (ALLOW, DENY, ASK, REWRITE, VOUCH):
            raise ValueError("unknown outcome: %r" % (outcome,))
        self.outcome = outcome
        self.reason = reason
        self.updated_input = updated_input
        self.evidence = evidence or {}
        self.context = context

    # constructors read better at call sites than Decision("deny", ...)
    @classmethod
    def allow(cls, reason=None, evidence=None, context=None):
        return cls(ALLOW, reason, evidence=evidence, context=context)

    @classmethod
    def deny(cls, reason, evidence=None, context=None):
        return cls(DENY, reason, evidence=evidence, context=context)

    @classmethod
    def ask(cls, reason, evidence=None, context=None):
        return cls(ASK, reason, evidence=evidence, context=context)

    @classmethod
    def rewrite(cls, updated_input, reason=None, evidence=None, context=None):
        return cls(REWRITE, reason, updated_input=updated_input, evidence=evidence, context=context)

    @classmethod
    def vouch(cls, reason=None, evidence=None, context=None):
        return cls(VOUCH, reason, evidence=evidence, context=context)

    def __repr__(self):  # pragma: no cover - debugging aid
        return "Decision(%s, %r)" % (self.outcome, self.reason)


def degraded_from(decision):
    """What this decision was before the dispatcher reduced it, or None.

    An adapter explaining why an outcome changed shape has to read this, not the outcome
    it was handed. A rewrite reduced to `ask` and then blocked by an agent that cannot
    prompt would otherwise be reported as a confirmation request that failed -- and it was
    never a confirmation request.
    """
    return (decision.evidence or {}).get("degraded_from")


def tool_input_of(raw):
    """The tool's arguments as a dict, decoding the JSON-string form some vendors send.

    `tool_input` is whatever the agent chose to serialise, and it is not always an object.
    Witnessed live on VS Code Copilot (2026-08-29), same adapter and same `Edit` tool, in
    two runs routed to different models: once as an object with path/old_str/new_str, once
    as a 129-character JSON *string*. Both are the vendor's real wire format.

    That difference is not cosmetic. Against the object the parser reports the file and the
    content; against the string it reported neither, so a policy denying on secret content
    saw an empty write and allowed it. The adapters guarded the string case against a crash
    (a crash is an allow) but resolved it to `{}`, which is a quieter version of the same
    outcome: the guard is blind and says nothing about it.

    Decoding is not a guess about an unrecorded shape -- a string that parses to a JSON
    object IS that object, and the alternative is discarding data the vendor sent. Only a
    dict counts: a JSON list or scalar is not a set of tool arguments, and `{}` remains the
    honest answer for anything that does not parse.
    """
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str) and raw[:1] == "{":
        try:
            parsed = _json.loads(raw)
        except Exception:
            return {}
        if isinstance(parsed, dict):
            return parsed
    return {}


# ------------------------------------------------------------------------------
# windows helper (used by the codex_cli adapter)

"""PowerShell's one rule that breaks hook commands, shared by the vendors it affects.

Two adapters here need this and for the same reason, so the explanation lives once rather
than twice: a copy that drifts is how a vendor fact becomes two disagreeing vendor facts.
"""



def powershell_command(command):
    """`command` rewritten so PowerShell will actually run it.

    A command line that BEGINS with a quoted path is parsed by PowerShell as a string
    expression, not an invocation -- and a bare string followed by more arguments is a
    parse error, so nothing runs at all. `&` is PowerShell's call operator, and it makes a
    quoted path executable.

    Witnessed live (Codex CLI 0.150.1, Windows, 2026-08-28): the quoted form failed with
    "hook exited with code 1" on every event, and a `> file 2>&1` redirect appended to it
    produced NO file -- proof the line never reached execution, since PowerShell sets up
    redirection only for a command it could parse. Prefixing `&` ran the hook immediately.
    A bare `python3 "..."` also works, because it parses in command mode; the difference is
    the leading quote, not the interpreter.

    Both vendors route hooks through PowerShell on Windows. Codex wraps them itself;
    VS Code Copilot does it in hookExecutor.ts's getShellCommand, which spawns
    `powershell.exe -ExecutionPolicy Bypass -NoProfile -NoLogo -Command <hookCommand>`
    whenever ComSpec is cmd.exe -- i.e. by default. Each adapter passes the result through
    its own per-platform override field, so the POSIX `command` keeps the exact quoted
    interpreter path that installed the hook.
    """
    return command if command.lstrip().startswith("&") else "& " + command


# ------------------------------------------------------------------------------
# codex_cli adapter

"""OpenAI Codex CLI adapter.

Verified against the vendor's hook engine source (openai/codex: config/src/hook_config.rs,
hooks/src/schema.rs, hooks/src/engine/output_parser.rs, hooks/src/engine/discovery.rs).

Codex speaks the Claude-family decision shape — hookSpecificOutput.permissionDecision with
allow/deny — and names its events in PASCALCASE, the same convention Claude Code uses:
`HookEventsToml`'s field renames in hook_config.rs ("PreToolUse", "PostToolUse", ...) are
what a hooks.json config file's event keys must match, and `HookEventNameWire`'s literal
constructions in schema.rs (`hook_event_name: "PreToolUse".to_string()`) confirm the same
casing on the runtime wire payload's own `hook_event_name` field. A previous version of this
adapter believed the events were camelCase, sourced from
app-server-protocol/schema/typescript/v2/HookEventName.ts -- that file is a ts-rs binding for
the App Server's separate IDE-facing JSON-RPC protocol, not the plain CLI hook-subprocess
dialect this adapter speaks; the two use different casing for the same event names.

Codex adds a turn-scoped `turn_id` field that Claude Code does not send -- the one field
that tells the two apart when the payload's event names are otherwise identical, since real
Claude Code event names are PascalCase too. `permission_mode` and `model` were both believed
exclusive to Codex at one point and both turned out to be shared (with Claude Code and Cursor
respectively); see `claims()`'s docstring.

"ask" is a rejected permissionDecision value at PreToolUse, per output_parser.rs's own
`unsupported_pre_tool_use_hook_specific_output`: Codex treats it as an invalid hook response
(not a real prompt), which Codex then handles by failing OPEN -- so `respond()` degrades ASK
to DENY with an explanatory reason there rather than emit a value the vendor's own parser
rejects.
"""



# Re-exported: callers and tests address this through the adapter that needs it, and the
# rule it encodes is a PowerShell fact two vendors share. See _windows.py.

AGENT = "codex_cli"

# hook_config.rs's HookEventsToml field renames, and schema.rs's HookEventNameWire /
# literal hook_event_name construction -- both PascalCase, matching Claude Code's own.
EVENT_MAP = {
    "PreToolUse": PRE_TOOL,
    "PostToolUse": POST_TOOL,
    "UserPromptSubmit": PROMPT_SUBMIT,
    "SessionStart": SESSION_START,
    "SessionEnd": SESSION_END,
    "PreCompact": PRE_COMPACT,
    "Stop": STOP,
    "SubagentStart": SUBAGENT_START,
    "SubagentStop": SUBAGENT_STOP,
    # PermissionRequest, PostCompact and Interrupt have no canonical counterpart yet;
    # leaving them unmapped keeps the matrix honest rather than inventing coverage.
}
REVERSE_EVENT_MAP = {v: k for k, v in EVENT_MAP.items()}


#: SessionStartCommandInput's fields, minus the event name. The struct is
#: deny_unknown_fields, so this is the whole payload -- there is nothing else to match on.
_SESSION_START_FIELDS = ("session_id", "transcript_path", "cwd", "model", "permission_mode", "source")


def claims(raw):
    """Codex's PreToolUse carries turn_id; Claude Code's does not.

    `model` used to count as a second marker and no longer does: Cursor's base hook schema
    sends `model` on every event, so claiming on it made every real Cursor payload
    ambiguous between the two adapters -- and an unidentified payload is allowed through.
    `permission_mode` used to count as a marker here too and no longer does either: a real
    live-captured Claude Code payload (2026-08-27, PreToolUse) carries `permission_mode`
    too -- confirmed once EVENT_MAP's casing was fixed to the vendor's actual PascalCase and
    codex_cli started claiming real Claude Code traffic that only `permission_mode` matched
    on. Two fields once believed exclusive to Codex have both turned out to be shared;
    `turn_id` is the one still unrefuted by a real captured payload.

    SessionStart is the exception, and it is claimed on shape instead. It is not
    turn-scoped, so Codex sends no turn_id there -- confirmed live (2026-08-28) and by
    `SessionStartCommandInput`, which is `deny_unknown_fields` and defines exactly the six
    fields below plus the event name. Every one of them is a field Claude Code also sends,
    so nothing here can tell the two apart. Claiming it anyway makes `detect()` DECLINE as
    ambiguous, which is the honest answer: before this, a real Codex SessionStart was
    claimed by claude_code alone and answered confidently in the wrong dialect, which Codex
    rejects (its output structs are deny_unknown_fields) and therefore fails open. Naming
    the agent explicitly is how a consumer resolves it, the same as tabnine and gemini_cli.
    """
    if not isinstance(raw, dict):
        return False
    name = raw.get("hook_event_name")
    if name not in EVENT_MAP:
        return False
    if "turn_id" in raw:
        return True
    return name == "SessionStart" and all(field in raw for field in _SESSION_START_FIELDS)


def parse(raw):
    """Normalise one payload.

    **A Codex write does not arrive with a path or content.** Live capture (2026-08-28, 36
    payloads) observed exactly two tool names -- `Bash` and `apply_patch` -- and BOTH carry
    only `tool_input.command`. `apply_patch` is the file-writing tool, and the patch text
    rides inside that command string. So on this agent a content policy has to gate on
    `event.command`; `event.content` and `event.path` stay None for a real write, and a
    handler written as `"SECRET" in (event.content or "")` will not fire here.

    `new_string`, `new_str` and `edits` used to be read alongside them. That was Claude
    Code's MultiEdit vocabulary copied across on the assumption Codex shared it; Codex has
    no such tool, and no payload has ever carried those keys. Removed rather than left to
    imply a coverage this adapter does not have. `content`/`file_path`/`path` are kept only
    as a generic fallback for MCP tools, whose tool_input this capture did not exercise.
    """
    ti = tool_input_of(raw.get("tool_input"))
    content = ti.get("content")
    return Event(
        AGENT,
        # An event this adapter has no mapping for resolves to UNKNOWN, never to the
        # nearest canonical one: relabelling it invites a guardrail to evaluate the
        # wrong policy against it.
        EVENT_MAP.get(raw.get("hook_event_name"), UNKNOWN),
        tool=raw.get("tool_name"),
        command=ti.get("command"),
        path=ti.get("file_path") or ti.get("path"),
        content=content,
        output=raw.get("tool_output"),
        prompt=raw.get("prompt"),
        session_id=raw.get("session_id"),
        tool_use_id=raw.get("tool_use_id"),
        cwd=raw.get("cwd"),
        raw=raw,
    )


def _because(reason, note):
    return "%s (%s)" % (reason, note) if reason else note


#: The two events whose refusal is a top-level {"decision": "block", "reason": ...} rather
#: than the PreToolUse permissionDecision gate. Their output structs
#: (UserPromptSubmitCommandOutputWire, StopCommandOutputWire) carry `decision:
#: BlockDecisionWire` -- whose ONLY value is "block" -- and no permissionDecision field at
#: all. Matches the matrix row: pre_tool, prompt_submit and stop are the blocking events.
_BLOCK_DIALECT_EVENTS = (PROMPT_SUBMIT, STOP)


#: Decision words this vendor HONOURS. "ask" is deliberately absent: it is in schema.rs's
#: PreToolUsePermissionDecisionWire, but output_parser.rs rejects it as an unsupported
#: response -- and a rejected response fails open, so emitting it would be worse than a deny.
DECISION_VOCABULARY = frozenset({"allow", "deny", "block"})


def respond(decision, event):
    """Always exit 0 and carry the verdict in JSON, in the dialect THIS event accepts.

    Codex wraps hook commands in `powershell -Command` on Windows, which collapses exit 2
    into exit 1 -- so an exit-code deny is silently downgraded to "the hook errored" on one
    platform. The JSON decision is the only representation that means the same thing
    everywhere.

    Every per-event output struct in hooks/src/schema.rs is `#[serde(deny_unknown_fields)]`,
    so a key that event does not define is not ignored: Codex rejects the whole response.
    Witnessed live (Codex CLI 0.150.1, 2026-08-28): sending the PreToolUse
    permissionDecision shape at UserPromptSubmit produced "hook returned invalid user prompt
    submit JSON output" on every prompt. Three dialects, one per group of events:

      * PRE_TOOL -- hookSpecificOutput.permissionDecision (deny, or allow WITH updatedInput)
      * PROMPT_SUBMIT / STOP -- top-level {"decision": "block", "reason": ...}
      * everything else -- no decision surface exists, so silence

    A bare allow is silence everywhere, including at PRE_TOOL: output_parser.rs's
    `unsupported_pre_tool_use_hook_specific_output` rejects permissionDecision:allow unless
    it carries updatedInput, and a rejected response is a hook error, which fails OPEN. An
    empty stdout is how this adapter says "no opinion", and it is the only spelling of allow
    Codex accepts at every event.
    """
    import json as _json

    if event.event == PRE_TOOL:
        return _pre_tool_response(decision)
    if event.event in _BLOCK_DIALECT_EVENTS:
        if decision.outcome in (DENY, ASK, REWRITE):
            return _json.dumps({"decision": "block", "reason": _refusal_reason(decision)}), 0
        return "", 0
    # Observation-only events. Codex defines no decision field for them (SessionEnd has no
    # output struct at all), so a verdict here would be rejected, not merely ignored.
    return "", 0


def _refusal_reason(decision):
    """The reason text for a refusal, annotated when the decision had to be degraded."""
    if decision.outcome == ASK:
        return _because(decision.reason, "Codex CLI cannot prompt for confirmation at this event")
    if decision.outcome == REWRITE:
        return _because(decision.reason, "Codex CLI cannot modify a tool call at this event")
    return decision.reason or "blocked by policy"


def _pre_tool_response(decision):
    """The permissionDecision gate, the one place Codex reads a permission verdict."""
    import json as _json

    out = {"hookEventName": "PreToolUse"}
    if decision.outcome == REWRITE and decision.updated_input is not None:
        # The only accepted spelling of allow: it must carry updatedInput.
        out["permissionDecision"] = "allow"
        out["updatedInput"] = decision.updated_input
        if decision.reason:
            out["permissionDecisionReason"] = decision.reason
    elif decision.outcome in (DENY, ASK, REWRITE):
        # ASK is rejected by Codex's own parser as an unsupported permissionDecision, and a
        # rejected response fails OPEN -- so asking would silently permit the very call the
        # handler wanted confirmed. A REWRITE with nothing to substitute is the same story.
        out["permissionDecision"] = "deny"
        note = None
        if decision.outcome == ASK:
            note = "Codex CLI does not support ask; asking would fail open"
        elif decision.outcome == REWRITE:
            note = "Codex CLI cannot apply a rewrite with no updatedInput"
        out["permissionDecisionReason"] = _because(decision.reason, note) if note else (decision.reason or "blocked")
    else:
        return "", 0  # allow: silence, since permissionDecision:allow alone is rejected
    return _json.dumps({"hookSpecificOutput": out}), 0


def hook_config(canonical_events, command, matcher=None):
    """ConfiguredHookMatcherGroup shape: {matcher, hooks: [{type: command, ...}]}.

    `commandWindows` is Codex's own per-platform override (HookHandlerConfig::Command in
    config/src/hook_config.rs; discovery.rs prefers it over `command` when cfg!(windows)).
    Using it keeps `command` as the POSIX form -- the exact interpreter that installed the
    hook, quoted -- while Windows gets the PowerShell-callable spelling, rather than trading
    a verified interpreter path for a bare `python3` and hoping PATH resolves it.
    """
    hooks = {}
    for ev in canonical_events:
        name = REVERSE_EVENT_MAP.get(ev)
        if not name:
            continue
        entry = {"hooks": [{"type": "command", "command": command, "commandWindows": powershell_command(command)}]}
        if matcher:
            entry["matcher"] = matcher
        hooks.setdefault(name, []).append(entry)
    return {"hooks": hooks}


CONFIG_PATH = ".codex/hooks.json"


# ------------------------------------------------------------------------------
# runtime (agentseam dispatch, specialized to codex_cli)

_VOUCH_SPEAKS = False
_REWRITE_EVENTS = frozenset(('pre_tool',))


def degrade(decision, event):
    """Reduce a decision to what 'codex_cli' can actually honor, honestly.

    This is agentseam.dispatch.degrade(), specialized to one fixed agent so this file needs
    no "import agentseam" -- no evidence establishes that an explicit approval word means anything beyond a plain allow here, so vouch degrades to one; see agentseam.allow_semantics.
    """
    if decision.outcome == REWRITE and event.event not in _REWRITE_EVENTS:
        evidence = dict(decision.evidence)
        evidence["degraded_from"] = REWRITE
        return Decision.ask(decision.reason or "input requires modification before it can run", evidence=evidence)
    if decision.outcome == VOUCH and not _VOUCH_SPEAKS:
        evidence = dict(decision.evidence)
        evidence["degraded_from"] = VOUCH
        return Decision.allow(decision.reason, evidence=evidence, context=decision.context)
    return decision


# >>> agentseam handler >>>
GUARD_VIOLATION = 1

_BASH_CANDIDATES = ('bash', 'C:\\Program Files\\Git\\usr\\bin\\bash.exe', 'C:\\Program Files\\Git\\bin\\bash.exe', 'C:\\Program Files (x86)\\Git\\usr\\bin\\bash.exe', '/bin/bash', '/usr/bin/bash')

GATE_LOG_ENV = 'CHOCK_GATE_LOG'

_LOG_MAX_BYTES = 1048576

_GUARD_TIMEOUT_SECONDS = 30

def guard_path_from_argv(argv: list[str]) -> _chock_Path | None:
    """The `--guard <path>` argument a vendored runtime was invoked with, or None.

    Read straight off argv rather than through argparse: every event a vendored runtime is
    ever invoked for goes through the same command line, chosen at install time
    (`hooks/*_install.py`), so there is nothing else on it to parse.
    """
    if '--guard' in argv:
        i = argv.index('--guard')
        if i + 1 < len(argv):
            return _chock_Path(argv[i + 1])
    return None

def find_bash(guard: _chock_Path) -> str | None:
    """First interpreter that can actually see `guard`, or None.

    The probe runs `test -f <guard>` rather than `--version`: the question is not whether
    a bash exists but whether *this* bash can resolve the path we are about to hand it.
    """
    for candidate in _BASH_CANDIDATES:
        try:
            proc = _chock_subprocess.run([candidate, '-c', f'test -f "{guard.as_posix()}"'], capture_output=True, timeout=10)
        except (OSError, _chock_subprocess.SubprocessError):
            continue
        if proc.returncode == 0:
            return candidate
    return None

def run_guard(guard: _chock_Path, command: str) -> bool | None:
    """True when the guard ran and reported a violation, False when it ran clean.

    None means the check did not happen -- unparseable command, no usable bash, a crash.
    That is distinct from False and must stay distinct: every "not checked" path still
    allows, so folding it into False changes no verdict, but it would let the outcome log
    record a passing guard for a check that never ran.

    Nothing here blocks on its own failure. Treating "could not run" as a violation would
    stop every Bash call the moment bash was missing -- turning a best-effort guard into a
    total outage. Failing open is stated loudly on stderr instead of silently.
    """
    try:
        args = _chock_shlex.split(command)
    except ValueError:
        print('chock: could not parse command (unbalanced quotes), not checked', file=sys.stderr)
        return None
    if not args:
        return None
    bash = find_bash(guard)
    if bash is None:
        print(f'chock: no usable bash found, {guard.name} not checked', file=sys.stderr)
        return None
    try:
        env = {**_chock_os.environ, 'CHOCK_RAW_COMMAND': command}
        proc = _chock_subprocess.run([bash, str(guard), *args], capture_output=True, text=True, encoding='utf-8', errors='replace', env=env, timeout=_GUARD_TIMEOUT_SECONDS)
    except (OSError, UnicodeError, _chock_subprocess.TimeoutExpired) as exc:
        print(f'chock: guard could not run, not checked: {exc}', file=sys.stderr)
        return None
    if proc.returncode == GUARD_VIOLATION:
        sys.stderr.write(proc.stdout or '')
        sys.stderr.write(proc.stderr or '')
        if not ((proc.stdout or '') + (proc.stderr or '')).strip():
            print(f'chock: blocked by {_chock_Path(guard).name} (guard gave no reason)', file=sys.stderr)
        return True
    if proc.returncode != 0:
        detail = (proc.stderr or proc.stdout or '').strip().splitlines()
        print(f'chock: guard exited {proc.returncode}, not checked' + (f': {detail[0][:120]}' if detail else ''), file=sys.stderr)
        return None
    return False

def log_outcome(guard: _chock_Path, tool: str, blocked: bool) -> None:
    """Append one outcome record. Best effort: never raises, never changes the verdict.

    Deliberately records NO command and no guard output. The command is the scanned content
    here, and commands routinely carry bearer tokens and passwords -- writing them to a
    plaintext file on every Bash call would create the exposure the secret policies exist to
    prevent. Which policy, which tool, and allow-or-block is the whole useful signal.
    """
    try:
        if _chock_os.environ.get(GATE_LOG_ENV) == '0':
            return
        guard = guard.resolve()
        if guard.parent.name != 'implementations':
            return
        artifact_root = None
        for parent in guard.parents:
            if (parent / '.chock').is_dir():
                artifact_root = parent / '.chock'
                break
        if artifact_root is None:
            return
        log_dir = artifact_root / 'log'
        log_dir.mkdir(parents=True, exist_ok=True)
        log_path = log_dir / 'gate-events.jsonl'
        if log_path.exists() and log_path.stat().st_size > _LOG_MAX_BYTES:
            log_path.replace(log_dir / 'gate-events.1.jsonl')
        import json
        record = {'ts': _chock_datetime.now(_chock_timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'), 'policy_id': guard.parent.parent.name, 'surface': 'pre-tool-use', 'event': 'tool_use', 'kind': guard.stem, 'tool': tool, 'verdict': 'block' if blocked else 'allow'}
        with log_path.open('a', encoding='utf-8') as fh:
            fh.write(json.dumps(record, ensure_ascii=False) + '\n')
    except Exception:
        return

def evaluate(argv: list[str], command: str, tool: str='') -> str | None:
    """Run the guard named on `argv` (`--guard <path>`) against `command`.

    Returns the deny reason when the guard reports a violation, None on allow (including
    every "not checked" case -- the guard's own stderr already explains those). The one
    caller-facing entry point `gate.runtime_bundle`'s spliced handler uses: locate the
    guard, run it, log the outcome, word the verdict.
    """
    guard = guard_path_from_argv(argv)
    if guard is None or not guard.exists():
        return None
    blocked = run_guard(guard, command)
    if blocked is not None:
        log_outcome(guard, tool, blocked)
    return f'Blocked by chock policy: {guard.stem}' if blocked else None


def handle(event):
    if event.event == "pre_tool" and event.command:
        reason = evaluate(sys.argv[1:], event.command, event.tool or "")
        return Decision.deny(reason) if reason else None
    return None
# <<< agentseam handler <<<


def _coerce(result):
    if result is None:
        return Decision.allow()
    if isinstance(result, Decision):
        return result
    raise TypeError("handle() must return a Decision or None, got %r" % (type(result),))


def _read_payload(stream):
    # Decode bytes ourselves rather than trust the platform locale -- a BOM'd or non-UTF-8
    # stdin must not silently disable the gate. See agentseam.dispatch for the incident
    # this guards: a Windows console's cp1252 layer turning a UTF-8 BOM into three bytes
    # json cannot parse, with the hook allowing everything while claiming enforcement.
    buffer = getattr(stream, "buffer", None)
    if buffer is not None:
        return buffer.read().decode("utf-8-sig", errors="replace")
    return stream.read().lstrip("\ufeff")


def _emit(out, text):
    buffer = getattr(out, "buffer", None)
    if buffer is not None:
        buffer.write(text.encode("utf-8"))
        buffer.flush()
    else:
        out.write(text)
        out.flush()


def main(stdin=None, stdout=None, exit=True):
    """Read one payload from stdin, dispatch, emit the 'codex_cli' response, exit."""
    stream = stdin if stdin is not None else sys.stdin
    out = stdout if stdout is not None else sys.stdout
    try:
        raw = json.loads(_read_payload(stream))
    except Exception:
        # Malformed input is not the agent's fault to pay for: allow, stay silent.
        if exit:
            sys.exit(0)
        return 0
    event = parse(raw)
    if event.event == UNKNOWN:
        # A vendor event this adapter has no mapping for. handle() is not called: it
        # reasons about the canonical vocabulary, and handing it something outside that
        # vocabulary invites a decision made on a false premise.
        if exit:
            sys.exit(0)
        return 0
    decision = degrade(_coerce(handle(event)), event)
    text, code = respond(decision, event)
    if text:
        _emit(out, text)
    if exit:
        sys.exit(code)
    return code


if __name__ == "__main__":  # pragma: no cover
    main()

